### PR TITLE
Update `FocusWithinRenderProps` interface

### LINKED ISSUE #5: Bug: Getting TS error when using FocusWithin
When using `FocusWithin`, TS throws the following error:
```
TS2339: Property 'focusProps' does not exist on type 'FocusWithinRenderProps'.
```
It's happening because `focusProps` is missing in 
```
export interface FocusWithinRenderProps {
    getFocusProps<P>(
        props?: P
    ): {
        onFocus(event: object): void
        onBlur(event: object): void
        onMouseDown(event: object): void
    } & P
    isFocused: boolean
}
```

### PR DESCRIPTION
**Pull request by steric85**
Fixes #5

### CODE REVIEW

**Comment by ferdaber** [comment]
Ah thanks for the fix!

**Comment by steric85** [comment]
Thanks @ferdaber!
When will the new version be published?

**Comment by ferdaber** [comment]
I just published v2.0.2.

**Comment by steric85** [comment]
Oh Great! Thank you!

**Pull request merged**
